[package]
name = "code-blog"
version = "0.1.0"
authors = ["Tom <tomgreenwood1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"